// Generated by tools/generate.py
#pragma once

#include <cstdint>

namespace ets2la_controller {

// Number of inputs the plugin registers with the game.
constexpr uint32_t kInputCount = 287;
// Number of analog axes (float inputs).
constexpr uint32_t kAxisCount = 26;

// Static description of one input, indexed by the numeric value of its Axis/Button enumerator.
struct ControlInfo {
    const char* scs_name;  // Name of the semantical mix in controls.sii.
    const char* name;      // Readable name, identical to the enumerator and the Python attribute.
    bool is_axis;          // true: float input, false: bool input.
};

// Analog inputs. Values are floats, clamped to [-1, 1] by the plugin.
enum class Axis : uint16_t {
    ui_left = 0,  // Menu navigation stick, left deflection (0 to 1). [SCS mix `j_left`]
    ui_right = 1,  // Menu navigation stick, right deflection (0 to 1). [SCS mix `j_right`]
    ui_up = 2,  // Menu navigation stick, up deflection (0 to 1). [SCS mix `j_up`]
    ui_down = 3,  // Menu navigation stick, down deflection (0 to 1). [SCS mix `j_down`]
    ui_scroll_x = 17,  // Analog horizontal scrolling in menus (-1 left, +1 right). [SCS mix `scroll_j_x`]
    ui_scroll_y = 18,  // Analog vertical scrolling in menus (-1 down, +1 up). (?) [SCS mix `scroll_j_y`]
    camera_look_x = 51,  // Relative camera yaw. (?) [SCS mix `camlr`]
    camera_look_y = 52,  // Relative camera pitch. (?) [SCS mix `camud`]
    camera_look_lr = 53,  // Camera look left/right stick (-1 left, +1 right). [SCS mix `j_cam_lk_lr`]
    camera_look_ud = 54,  // Camera look up/down stick (-1 down, +1 up). (?) [SCS mix `j_cam_lk_ud`]
    camera_move_lr = 55,  // Free camera move left/right stick (-1 left, +1 right). [SCS mix `j_cam_mv_lr`]
    camera_move_ud = 56,  // Free camera move forward/back stick (-1 back, +1 forward). (?) [SCS mix `j_cam_mv_ud`]
    trs_zoom_in_axis = 57,  // Analog zoom in for the truck/trailer view (0 to 1). [SCS mix `j_trzoom_in`]
    trs_zoom_out_axis = 58,  // Analog zoom out for the truck/trailer view (0 to 1). [SCS mix `j_trzoom_out`]
    map_pan_x = 64,  // Pan the map horizontally (-1 left, +1 right). [SCS mix `j_mappan_x`]
    map_pan_y = 65,  // Pan the map vertically (-1 down, +1 up). (?) [SCS mix `j_mappan_y`]
    map_zoom_in_axis = 66,  // Analog map zoom in (0 to 1). [SCS mix `j_mapzom_in`]
    map_zoom_out_axis = 67,  // Analog map zoom out (0 to 1). [SCS mix `j_mapzom_out`]
    steering = 79,  // Steering, -1 = full left, +1 = full right. [SCS mix `steering`]
    throttle = 80,  // Throttle pedal, 0 = released, 1 = full. (?) [SCS mix `aforward`]
    brake = 81,  // Service brake pedal, 0 = released, 1 = full. [SCS mix `abackward`]
    clutch = 82,  // Clutch pedal, 0 = released, 1 = fully pressed. [SCS mix `clutch`]
    photo_zoom_out_axis = 193,  // Analog photo camera zoom out (0 to 1). [SCS mix `phot_z_j_out`]
    photo_zoom_in_axis = 194,  // Analog photo camera zoom in (0 to 1). [SCS mix `phot_z_j_in`]
    walk_look_lr = 213,  // Walking camera look left/right. (?) [SCS mix `camwalk_lr`]
    walk_look_ud = 214,  // Walking camera look up/down. (?) [SCS mix `camwalk_ud`]
};

// Digital inputs (true = pressed). Hold inputs use set(), press inputs use press().
enum class Button : uint16_t {
    ui_select = 4,  // [Press] Confirm the focused menu entry. [SCS mix `selectfcs`, default key: Enter / Numpad Enter]
    ui_back = 5,  // [Press] Go back one menu level. [SCS mix `back`, default key: Esc]
    ui_skip = 6,  // [Press] Skip the current screen or cutscene. [SCS mix `skip`, default key: Esc]
    ui_scroll_up = 7,  // [Press] Scroll lists up by one step. [SCS mix `scrol_up`, default key: Mouse wheel up]
    ui_scroll_down = 8,  // [Press] Scroll lists down by one step. [SCS mix `scrol_dwn`, default key: Mouse wheel down]
    map_zoom_in = 9,  // [Press] Zoom the map in by one step. [SCS mix `mapzoom_in`, default key: Mouse wheel up]
    map_zoom_out = 10,  // [Press] Zoom the map out by one step. [SCS mix `mapzoom_out`, default key: Mouse wheel down]
    trs_zoom_in = 11,  // [Press] Zoom in by one step in the truck/trailer view. [SCS mix `trs_zoom_in`, default key: Mouse wheel up]
    trs_zoom_out = 12,  // [Press] Zoom out by one step in the truck/trailer view. [SCS mix `trs_zoom_out`, default key: Mouse wheel down]
    ui_nav_previous = 13,  // [Press] Gamepad menu navigation: previous entry. [SCS mix `joy_nav_prv`]
    ui_nav_next = 14,  // [Press] Gamepad menu navigation: next entry. [SCS mix `joy_nav_nxt`]
    ui_section_previous = 15,  // [Press] Gamepad menu navigation: previous section or tab. [SCS mix `joy_sec_prv`]
    ui_section_next = 16,  // [Press] Gamepad menu navigation: next section or tab. [SCS mix `joy_sec_nxt`]
    shortcut_1 = 19,  // [Press] Menu shortcut button 1. [SCS mix `shortcut_1`]
    shortcut_1_hold = 20,  // [Hold] Hold variant of shortcut 1. (?) [SCS mix `shortcut_1h`]
    shortcut_2 = 21,  // [Press] Menu shortcut button 2. [SCS mix `shortcut_2`]
    shortcut_2_hold = 22,  // [Hold] Hold variant of shortcut 2. (?) [SCS mix `shortcut_2h`]
    shortcut_3 = 23,  // [Press] Menu shortcut button 3. [SCS mix `shortcut_3`]
    shortcut_3_hold = 24,  // [Hold] Hold variant of shortcut 3. (?) [SCS mix `shortcut_3h`]
    shortcut_4 = 25,  // [Press] Menu shortcut button 4. [SCS mix `shortcut_4`]
    shortcut_4_hold = 26,  // [Hold] Hold variant of shortcut 4. (?) [SCS mix `shortcut_4h`]
    pause = 27,  // [Press] Pause or resume the game. [SCS mix `pause`, default key: Pause]
    screenshot = 28,  // [Press] Take a screenshot. [SCS mix `screenshot`]
    camera_1 = 29,  // [Press] Select camera slot 1. [SCS mix `cam1`, default key: 1]
    camera_2 = 30,  // [Press] Select camera slot 2. [SCS mix `cam2`, default key: 2]
    camera_3 = 31,  // [Press] Select camera slot 3. [SCS mix `cam3`, default key: 3]
    camera_4 = 32,  // [Press] Select camera slot 4. [SCS mix `cam4`, default key: 4]
    camera_5 = 33,  // [Press] Select camera slot 5. [SCS mix `cam5`, default key: 5]
    camera_6 = 34,  // [Press] Select camera slot 6. [SCS mix `cam6`, default key: 6]
    camera_7 = 35,  // [Press] Select camera slot 7. [SCS mix `cam7`, default key: 7]
    camera_8 = 36,  // [Press] Select camera slot 8. [SCS mix `cam8`, default key: 8]
    camera_cycle = 37,  // [Press] Cycle to the next camera. [SCS mix `camcycle`, default key: 9]
    camera_reset = 38,  // [Press] Reset the current camera to its default position. [SCS mix `camreset`]
    camera_rotate = 39,  // [Hold] Rotate the free camera while true. [SCS mix `camrotate`, default key: Right mouse button]
    camera_zoom_in = 40,  // [Press] Zoom the camera in by one step. [SCS mix `camzoomin`, default key: Mouse wheel up]
    camera_zoom_out = 41,  // [Press] Zoom the camera out by one step. [SCS mix `camzoomout`, default key: Mouse wheel down]
    camera_zoom_drag = 42,  // [Hold] Zoom the camera while true. [SCS mix `camzoom`, default key: Middle mouse button]
    camera_move_forward = 43,  // [Hold] Move the free camera forward. [SCS mix `camfwd`, default key: Numpad 8]
    camera_move_back = 44,  // [Hold] Move the free camera backward. [SCS mix `camback`, default key: Numpad 5]
    camera_move_left = 45,  // [Hold] Move the free camera left. [SCS mix `camleft`, default key: Numpad 4]
    camera_move_right = 46,  // [Hold] Move the free camera right. [SCS mix `camright`, default key: Numpad 6]
    camera_move_up = 47,  // [Hold] Move the free camera up. [SCS mix `camup`, default key: Numpad 9]
    camera_move_down = 48,  // [Hold] Move the free camera down. [SCS mix `camdown`, default key: Numpad 3]
    look_left = 49,  // [Hold] Look left while true. [SCS mix `lookleft`]
    look_right = 50,  // [Hold] Look right while true. [SCS mix `lookright`]
    trs_camera_reset = 59,  // [Press] Reset the camera in the truck/trailer view. [SCS mix `j_tr_cam_res`, default key: R]
    trs_camera_switch = 60,  // [Press] Switch the camera in the truck/trailer view. [SCS mix `j_tr_cam_swi`, default key: C]
    trs_lights = 61,  // [Press] Toggle the lights in the truck/trailer view. [SCS mix `j_tr_lights`, default key: L]
    trs_fullscreen = 62,  // [Press] Toggle full-screen in the truck/trailer view. [SCS mix `j_tr_fullsc`, default key: F]
    trs_attach_trailer = 63,  // [Press] Attach or detach the trailer from the truck/trailer view. [SCS mix `j_tr_att_tra`, default key: T]
    look_position_1 = 68,  // [Press] Snap the head look to preset 1. [SCS mix `lookpos1`, default key: Numpad 5]
    look_position_2 = 69,  // [Press] Snap the head look to preset 2. [SCS mix `lookpos2`, default key: Numpad 9]
    look_position_3 = 70,  // [Press] Snap the head look to preset 3. [SCS mix `lookpos3`, default key: Numpad 7]
    look_position_4 = 71,  // [Press] Snap the head look to preset 4. [SCS mix `lookpos4`, default key: Numpad 6]
    look_position_5 = 72,  // [Press] Snap the head look to preset 5. [SCS mix `lookpos5`, default key: Numpad 4]
    look_position_6 = 73,  // [Press] Snap the head look to preset 6. [SCS mix `lookpos6`, default key: Numpad 8]
    look_position_7 = 74,  // [Press] Snap the head look to preset 7. [SCS mix `lookpos7`]
    look_position_8 = 75,  // [Press] Snap the head look to preset 8. [SCS mix `lookpos8`]
    look_position_9 = 76,  // [Press] Snap the head look to preset 9. [SCS mix `lookpos9`]
    look_steer = 77,  // [Hold] Head follows the steering direction while true. (?) [SCS mix `looksteer`]
    look_blinker = 78,  // [Hold] Head looks toward the active blinker side while true. (?) [SCS mix `lookblink`]
    activate = 83,  // [Press] Confirm or interact. [SCS mix `activate`, default key: Enter / Numpad Enter]
    menu = 84,  // [Press] Open the pause menu or close the current window. [SCS mix `menu`, default key: Esc]
    engine_toggle = 85,  // [Press] Toggle the engine on or off. [SCS mix `engine`, default key: C]
    engine_electrics = 86,  // [Press] Toggle the truck electrics. (?) [SCS mix `engineelect`]
    ignition_off = 87,  // [Press] Turn the ignition off. [SCS mix `ignitionoff`]
    ignition_on = 88,  // [Press] Turn the ignition on. [SCS mix `ignitionon`]
    ignition_start = 89,  // [Hold] Crank the starter while true. [SCS mix `ignitionstrt`]
    attach_trailer = 90,  // [Press] Attach or detach the trailer. [SCS mix `attach`, default key: T]
    suspension_front_up = 91,  // [Press] Raise the front suspension. [SCS mix `frontsuspup`]
    suspension_front_down = 92,  // [Press] Lower the front suspension. [SCS mix `frontsuspdwn`]
    suspension_rear_up = 93,  // [Press] Raise the rear suspension. [SCS mix `rearsuspup`]
    suspension_rear_down = 94,  // [Press] Lower the rear suspension. [SCS mix `rearsuspdwn`]
    suspension_reset = 95,  // [Press] Reset the suspension to its default height. [SCS mix `suspreset`]
    horn = 96,  // [Hold] Horn while true. [SCS mix `horn`, default key: H]
    air_horn = 97,  // [Hold] Air horn while true. [SCS mix `airhorn`]
    light_flash = 98,  // [Hold] Flash the headlights while true. [SCS mix `lighthorn`]
    beacon = 99,  // [Press] Toggle the roof beacon. [SCS mix `beacon`]
    motor_brake = 100,  // [Hold] Engine brake while true. (?) [SCS mix `motorbrake`]
    engine_brake_toggle = 101,  // [Press] Toggle the engine brake. [SCS mix `engbraketog`]
    engine_brake_up = 102,  // [Press] Engine brake: next stronger level. [SCS mix `engbrakeup`]
    engine_brake_down = 103,  // [Press] Engine brake: next weaker level. [SCS mix `engbrakedwn`]
    trailer_brake = 104,  // [Hold] Trailer brake only, while true. [SCS mix `trailerbrake`]
    retarder_up = 105,  // [Press] Retarder: next stronger level. [SCS mix `retarderup`]
    retarder_down = 106,  // [Press] Retarder: next weaker level. [SCS mix `retarderdown`]
    retarder_0 = 107,  // [Press] Set retarder to level 0. [SCS mix `retarder0`]
    retarder_1 = 108,  // [Press] Set retarder to level 1. [SCS mix `retarder1`]
    retarder_2 = 109,  // [Press] Set retarder to level 2. [SCS mix `retarder2`]
    retarder_3 = 110,  // [Press] Set retarder to level 3. [SCS mix `retarder3`]
    retarder_4 = 111,  // [Press] Set retarder to level 4. [SCS mix `retarder4`]
    retarder_5 = 112,  // [Press] Set retarder to level 5. [SCS mix `retarder5`]
    lift_axle = 113,  // [Press] Raise or lower the truck lift axle. [SCS mix `liftaxle`]
    lift_axle_trailer = 114,  // [Press] Raise or lower the trailer lift axle. [SCS mix `liftaxlet`]
    slide_axle_forward = 115,  // [Hold] Slide the trailer axles forward while true. [SCS mix `slideaxlefwd`]
    slide_axle_backward = 116,  // [Hold] Slide the trailer axles backward while true. [SCS mix `slideaxlebwd`]
    slide_axle_manual = 117,  // [Press] Toggle manual trailer axle sliding. (?) [SCS mix `slideaxleman`]
    trailer_suspension_up = 118,  // [Press] Raise the trailer suspension. [SCS mix `trlrsuspup`]
    trailer_suspension_down = 119,  // [Press] Lower the trailer suspension. [SCS mix `trlrsuspdwn`]
    differential_lock = 120,  // [Press] Toggle the differential lock. [SCS mix `diflock`, default key: R]
    window_right_open = 121,  // [Hold] Open the right window while true. [SCS mix `rwinopen`, default key: ']
    window_right_close = 122,  // [Hold] Close the right window while true. [SCS mix `rwinclose`, default key: []
    window_left_open = 123,  // [Hold] Open the left window while true. [SCS mix `lwinopen`, default key: ;]
    window_left_close = 124,  // [Hold] Close the left window while true. [SCS mix `lwinclose`, default key: P]
    engine_brake_auto = 125,  // [Press] Toggle automatic engine brake. [SCS mix `engbrakeauto`]
    retarder_auto = 126,  // [Press] Toggle automatic retarder. [SCS mix `retarderauto`]
    embrake = 127,  // [Press] EM brake toggle. (?) [SCS mix `embrake`]
    lane_assist_mode = 128,  // [Press] Switch the lane assist mode. (?) [SCS mix `laneassmode`]
    transmission_power_mode = 129,  // [Press] Switch the transmission power mode. (?) [SCS mix `tranpwrmode`]
    parking_brake = 130,  // [Press] Toggle the parking brake. [SCS mix `parkingbrake`, default key: Space]
    handbrake = 131,  // [Hold] Hand brake while true. (?) [SCS mix `handbrake`]
    wipers_step_up = 132,  // [Press] Step the wipers to the next higher level. [SCS mix `wipers`, default key: .]
    wipers_step_down = 133,  // [Press] Step the wipers to the next lower level. [SCS mix `wipersback`, default key: ,]
    wipers_level_0 = 134,  // [Press] Set the wipers directly to level 0. [SCS mix `wipers0`]
    wipers_level_1 = 135,  // [Press] Set the wipers directly to level 1. [SCS mix `wipers1`]
    wipers_level_2 = 136,  // [Press] Set the wipers directly to level 2. [SCS mix `wipers2`]
    wipers_level_3 = 137,  // [Press] Set the wipers directly to level 3. [SCS mix `wipers3`]
    wipers_level_4 = 138,  // [Press] Set the wipers directly to level 4. [SCS mix `wipers4`]
    cruise_control = 139,  // [Press] Toggle cruise control. [SCS mix `cruiectrl`]
    cruise_control_increase = 140,  // [Press] Increase the cruise control speed. [SCS mix `cruiectrlinc`]
    cruise_control_decrease = 141,  // [Press] Decrease the cruise control speed. [SCS mix `cruiectrldec`]
    cruise_control_resume = 142,  // [Press] Resume cruise control at the last set speed. [SCS mix `cruiectrlres`]
    acc_mode = 143,  // [Press] Switch the adaptive cruise control mode. (?) [SCS mix `accmode`]
    lane_assist = 144,  // [Press] Toggle lane assist. [SCS mix `laneassist`]
    lights_cycle = 145,  // [Press] Cycle the lights. [SCS mix `light`, default key: L]
    lights_off = 146,  // [Press] Lights off. [SCS mix `lightoff`]
    lights_parking = 147,  // [Press] Parking lights. [SCS mix `lightpark`]
    lights_on = 148,  // [Press] Low beam on. [SCS mix `lighton`]
    high_beam = 149,  // [Press] Toggle the high beams. [SCS mix `hblight`, default key: K]
    blinker_left = 150,  // [Press] Left blinker toggle. [SCS mix `lblinker`, default key: Q]
    blinker_left_hold = 151,  // [Hold] Left blinker while true. (?) [SCS mix `lblinkerh`]
    blinker_right = 152,  // [Press] Right blinker toggle. [SCS mix `rblinker`, default key: E]
    blinker_right_hold = 153,  // [Hold] Right blinker while true. (?) [SCS mix `rblinkerh`]
    hazard_lights = 154,  // [Press] Toggle the hazard lights. [SCS mix `flasher4way`, default key: x56]
    show_mirrors = 155,  // [Press] Toggle the mirror views. (?) [SCS mix `showmirrors`, default key: F2]
    show_hud = 156,  // [Press] Toggle the HUD. [SCS mix `showhud`, default key: F3]
    navigation_map = 157,  // [Press] Toggle the full-screen navigation map. [SCS mix `navmap`, default key: M]
    photo_mode = 158,  // [Press] Enter or leave photo mode. [SCS mix `photo_mode`]
    quick_save = 159,  // [Press] Quick-save the game. [SCS mix `quicksave`, default key: Scroll Lock]
    quick_load = 160,  // [Press] Quick-load the last quick-save. [SCS mix `quickload`]
    aca_quick_reset = 161,  // [Press] Advanced coupling assistant quick action. (?) [SCS mix `acaquickr`]
    radio = 162,  // [Press] Toggle the radio on or off. [SCS mix `radio`]
    radio_next = 163,  // [Press] Next radio station. [SCS mix `radionext`, default key: Page Down]
    radio_previous = 164,  // [Press] Previous radio station. [SCS mix `radioprev`, default key: Page Up]
    radio_up = 165,  // [Press] Radio up, volume or station. (?) [SCS mix `radioup`]
    radio_down = 166,  // [Press] Radio down, volume or station. (?) [SCS mix `radiodown`]
    display_cycle = 167,  // [Press] Cycle the dashboard display page. (?) [SCS mix `display`, default key: I]
    quick_park = 168,  // [Press] Quick-park the truck. [SCS mix `quickpark`, default key: Q]
    dashboard_map_zoom = 169,  // [Press] Change the zoom of the dashboard navigation display. [SCS mix `dashmapzoom`]
    trip_reset = 170,  // [Press] Reset the trip meter. [SCS mix `tripreset`]
    sidebar_activate = 171,  // [Press] Activate the sidebar panel. (?) [SCS mix `sb_activate`, default key: Tab]
    sidebar_swap = 172,  // [Press] Swap the sidebar panel. (?) [SCS mix `sb_swap`, default key: Caps Lock]
    infotainment = 173,  // [Press] Toggle the infotainment screen. (?) [SCS mix `infotainment`]
    map_center = 174,  // [Press] Re-center the map on the truck. [SCS mix `mapcenter`, default key: F]
    photo_reset = 175,  // [Press] Reset the photo camera. [SCS mix `photores`, default key: R]
    photo_move = 176,  // [Hold] Move the photo camera while true. (?) [SCS mix `photomove`, default key: Right mouse button]
    photo_grab = 177,  // [Hold] Grab and rotate the photo camera while true. (?) [SCS mix `phototake`, default key: Left mouse button]
    photo_forward = 178,  // [Hold] Photo camera forward. [SCS mix `photofwd`, default key: W]
    photo_backward = 179,  // [Hold] Photo camera backward. [SCS mix `photobwd`, default key: S]
    photo_left = 180,  // [Hold] Photo camera left. [SCS mix `photoleft`, default key: A]
    photo_right = 181,  // [Hold] Photo camera right. [SCS mix `photoright`, default key: D]
    photo_up = 182,  // [Hold] Photo camera up. [SCS mix `photoup`, default key: Q]
    photo_down = 183,  // [Hold] Photo camera down. [SCS mix `photodown`, default key: E]
    photo_roll_left = 184,  // [Hold] Roll the photo camera left. [SCS mix `photorolll`, default key: Z]
    photo_roll_right = 185,  // [Hold] Roll the photo camera right. [SCS mix `photorollr`, default key: C]
    photo_manager = 186,  // [Press] Open the photo manager. (?) [SCS mix `photosman`, default key: M]
    photo_options = 187,  // [Press] Open the photo options. [SCS mix `photo_opts`, default key: Space]
    photo_snap = 188,  // [Press] Take the photo. [SCS mix `photosnap`, default key: Enter]
    photo_hide_controls = 189,  // [Press] Hide or show the photo mode controls. [SCS mix `photo_hctrl`, default key: H]
    photo_names = 190,  // [Press] Toggle names in photo mode. (?) [SCS mix `photonames`, default key: N]
    photo_zoom_out = 191,  // [Press] Photo camera zoom out by one step. [SCS mix `photozoomout`, default key: Mouse wheel down]
    photo_zoom_in = 192,  // [Press] Photo camera zoom in by one step. [SCS mix `photozoomin`, default key: Mouse wheel up]
    album_page_up = 195,  // [Press] Album: previous page. [SCS mix `album_pgup`, default key: Page Up]
    album_page_down = 196,  // [Press] Album: next page. [SCS mix `album_pgdn`, default key: Page Down]
    album_item_up = 197,  // [Press] Album: move the selection up. [SCS mix `album_itup`, default key: Up]
    album_item_down = 198,  // [Press] Album: move the selection down. [SCS mix `album_itdn`, default key: Down]
    album_item_left = 199,  // [Press] Album: move the selection left. [SCS mix `album_itlf`, default key: Left]
    album_item_right = 200,  // [Press] Album: move the selection right. [SCS mix `album_itrg`, default key: Right]
    album_item_home = 201,  // [Press] Album: jump to the first item. [SCS mix `album_ithm`, default key: Home]
    album_item_end = 202,  // [Press] Album: jump to the last item. [SCS mix `album_iten`, default key: End]
    album_item_activate = 203,  // [Press] Album: open the selected item. [SCS mix `album_itac`, default key: Enter / Numpad Enter]
    album_item_options = 204,  // [Press] Album: options for the selected item. (?) [SCS mix `album_itop`, default key: Space]
    album_item_delete = 205,  // [Press] Album: delete the selected item. [SCS mix `album_itdl`, default key: Delete]
    walk_forward = 206,  // [Hold] Walk forward. [SCS mix `camwalk_for`, default key: W]
    walk_backward = 207,  // [Hold] Walk backward. [SCS mix `camwalk_back`, default key: S]
    walk_right = 208,  // [Hold] Walk right. [SCS mix `camwalk_righ`, default key: D]
    walk_left = 209,  // [Hold] Walk left. [SCS mix `camwalk_left`, default key: A]
    walk_run = 210,  // [Hold] Run while true. [SCS mix `camwalk_run`, default key: Left Shift]
    walk_jump = 211,  // [Press] Jump. [SCS mix `camwalk_jump`, default key: Space]
    walk_crouch = 212,  // [Hold] Crouch while true. [SCS mix `camwalk_crou`, default key: Left Ctrl]
    gear_up = 215,  // [Press] Shift up one gear. [SCS mix `gearup`, default key: Left Shift / Right Shift]
    gear_down = 216,  // [Press] Shift down one gear. [SCS mix `geardown`, default key: Left Ctrl / Right Ctrl]
    gear_neutral = 217,  // [Press] Shift to neutral. [SCS mix `gear0`]
    gear_drive = 218,  // [Press] Shift to drive. [SCS mix `geardrive`]
    gear_reverse = 219,  // [Press] Shift to reverse. [SCS mix `gearreverse`]
    gear_up_hint = 220,  // [Press] Shift up using the shift hint. (?) [SCS mix `gearuphint`]
    gear_down_hint = 221,  // [Press] Shift down using the shift hint. (?) [SCS mix `geardownhint`]
    transmission_semi = 222,  // [Press] Toggle the semi-automatic transmission mode. (?) [SCS mix `transemi`]
    drive = 223,  // [Press] Select drive. [SCS mix `drive`]
    reverse = 224,  // [Press] Select reverse. [SCS mix `reverse`]
    mirror_select_cabin = 225,  // [Press] Select the cabin mirror for adjusting. (?) [SCS mix `cmirrorsel`]
    mirror_select_front = 226,  // [Press] Select the front mirror for adjusting. (?) [SCS mix `fmirrorsel`]
    mirror_yaw_left = 227,  // [Hold] Turn the selected mirror left while true. [SCS mix `mirroryawl`]
    mirror_yaw_right = 228,  // [Hold] Turn the selected mirror right while true. [SCS mix `mirroryawr`]
    mirror_pitch_up = 229,  // [Hold] Tilt the selected mirror up while true. [SCS mix `mirrorpitu`]
    mirror_pitch_down = 230,  // [Hold] Tilt the selected mirror down while true. (?) [SCS mix `mirrorpitl`]
    mirror_reset = 231,  // [Press] Reset the selected mirror. [SCS mix `mirrorreset`]
    quick_select_1 = 232,  // [Press] Quick-select slot 1. [SCS mix `quicksel1`, default key: 1 / Numpad 1]
    quick_select_2 = 233,  // [Press] Quick-select slot 2. [SCS mix `quicksel2`, default key: 2 / Numpad 2]
    quick_select_3 = 234,  // [Press] Quick-select slot 3. [SCS mix `quicksel3`, default key: 3 / Numpad 3]
    quick_select_4 = 235,  // [Press] Quick-select slot 4. [SCS mix `quicksel4`, default key: 4 / Numpad 4]
    quick_select_5 = 236,  // [Press] Quick-select slot 5. [SCS mix `quicksel5`, default key: 5 / Numpad 5]
    quick_select_6 = 237,  // [Press] Quick-select slot 6. [SCS mix `quicksel6`, default key: 6 / Numpad 6]
    quick_select_7 = 238,  // [Press] Quick-select slot 7. [SCS mix `quicksel7`, default key: 7 / Numpad 7]
    quick_select_8 = 239,  // [Press] Quick-select slot 8. [SCS mix `quicksel8`, default key: 8 / Numpad 8]
    push_to_talk = 240,  // [Hold] Multiplayer push-to-talk while true. [SCS mix `mpptt`]
    replay_hide_controls = 241,  // [Press] Hide or show the replay controls. [SCS mix `replayhidec`, default key: H]
    gear_selector_1_on = 242,  // [Press] Gear selector 1 on. (?) [SCS mix `gearsel1on`]
    gear_selector_1_off = 243,  // [Press] Gear selector 1 off. (?) [SCS mix `gearsel1off`]
    gear_selector_1_toggle = 244,  // [Press] Gear selector 1 toggle. (?) [SCS mix `gearsel1tgl`]
    gear_selector_2_on = 245,  // [Press] Gear selector 2 on. (?) [SCS mix `gearsel2on`]
    gear_selector_2_off = 246,  // [Press] Gear selector 2 off. (?) [SCS mix `gearsel2off`]
    gear_selector_2_toggle = 247,  // [Press] Gear selector 2 toggle. (?) [SCS mix `gearsel2tgl`]
    gear_1 = 248,  // [Press] Select gear 1 directly. [SCS mix `gear1`]
    gear_2 = 249,  // [Press] Select gear 2 directly. [SCS mix `gear2`]
    gear_3 = 250,  // [Press] Select gear 3 directly. [SCS mix `gear3`]
    gear_4 = 251,  // [Press] Select gear 4 directly. [SCS mix `gear4`]
    gear_5 = 252,  // [Press] Select gear 5 directly. [SCS mix `gear5`]
    gear_6 = 253,  // [Press] Select gear 6 directly. [SCS mix `gear6`]
    gear_7 = 254,  // [Press] Select gear 7 directly. [SCS mix `gear7`]
    gear_8 = 255,  // [Press] Select gear 8 directly. [SCS mix `gear8`]
    gear_9 = 256,  // [Press] Select gear 9 directly. [SCS mix `gear9`]
    gear_10 = 257,  // [Press] Select gear 10 directly. [SCS mix `gear10`]
    gear_11 = 258,  // [Press] Select gear 11 directly. [SCS mix `gear11`]
    gear_12 = 259,  // [Press] Select gear 12 directly. [SCS mix `gear12`]
    gear_13 = 260,  // [Press] Select gear 13 directly. [SCS mix `gear13`]
    gear_14 = 261,  // [Press] Select gear 14 directly. [SCS mix `gear14`]
    gear_15 = 262,  // [Press] Select gear 15 directly. [SCS mix `gear15`]
    gear_16 = 263,  // [Press] Select gear 16 directly. [SCS mix `gear16`]
    adjuster = 264,  // [Press] Open the seat/mirror/light adjuster. [SCS mix `adjuster`, default key: F4]
    advisor_mouse = 265,  // [Press] Advisor: toggle mouse control. (?) [SCS mix `advmouse`, default key: F1]
    advisor_eta_mode = 266,  // [Press] Advisor: switch the ETA mode. (?) [SCS mix `advetamode`]
    garage_manager = 267,  // [Press] Open the garage manager. (?) [SCS mix `gar_man`, default key: G]
    advisor_zoom_in = 268,  // [Press] Advisor: zoom in. (?) [SCS mix `advzoomin`]
    advisor_zoom_out = 269,  // [Press] Advisor: zoom out. (?) [SCS mix `advzoomout`, default key: F5]
    advisor_options = 270,  // [Press] Advisor: open the options. [SCS mix `advoptions`, default key: F6]
    advisor_services = 271,  // [Press] Advisor: open the services. [SCS mix `services`, default key: F7]
    assist_action_1 = 272,  // [Press] Driving assist action 1. (?) [SCS mix `assistact1`, default key: 1]
    assist_action_2 = 273,  // [Press] Driving assist action 2. (?) [SCS mix `assistact2`, default key: 2]
    assist_action_3 = 274,  // [Press] Driving assist action 3. (?) [SCS mix `assistact3`, default key: 3]
    assist_action_4 = 275,  // [Press] Driving assist action 4. (?) [SCS mix `assistact4`, default key: 4]
    assist_action_5 = 276,  // [Press] Driving assist action 5. (?) [SCS mix `assistact5`, default key: 5]
    adjust_seats = 277,  // [Press] Adjuster: seats. [SCS mix `adj_seats`, default key: 1]
    adjust_mirrors = 278,  // [Press] Adjuster: mirrors. [SCS mix `adj_mirrors`, default key: 2]
    adjust_lights = 279,  // [Press] Adjuster: lights. [SCS mix `adj_lights`, default key: 3]
    adjust_ui_mirror = 280,  // [Press] Adjuster: UI mirror. (?) [SCS mix `adj_uimirror`, default key: 4]
    chat_open = 281,  // [Press] Open the multiplayer chat input. [SCS mix `chat_act`, default key: Y]
    quick_chat = 282,  // [Press] Open the multiplayer quick-chat wheel. (?) [SCS mix `quick_chat`]
    zoom_cycle = 283,  // [Press] Cycle through the zoom levels of the current view. [SCS mix `cycl_zoom`, default key: Tab]
    name_tags = 284,  // [Press] Toggle player name tags in multiplayer. [SCS mix `name_tags`, default key: Z]
    head_reset = 285,  // [Press] Re-center head tracking or VR view. [SCS mix `headreset`, default key: F12]
    stereo_menu = 286,  // [Press] Toggle the stereo or VR menu mode. (?) [SCS mix `menustereo`, default key: F11]
};

inline constexpr ControlInfo kControls[kInputCount] = {
    {"j_left", "ui_left", true},
    {"j_right", "ui_right", true},
    {"j_up", "ui_up", true},
    {"j_down", "ui_down", true},
    {"selectfcs", "ui_select", false},
    {"back", "ui_back", false},
    {"skip", "ui_skip", false},
    {"scrol_up", "ui_scroll_up", false},
    {"scrol_dwn", "ui_scroll_down", false},
    {"mapzoom_in", "map_zoom_in", false},
    {"mapzoom_out", "map_zoom_out", false},
    {"trs_zoom_in", "trs_zoom_in", false},
    {"trs_zoom_out", "trs_zoom_out", false},
    {"joy_nav_prv", "ui_nav_previous", false},
    {"joy_nav_nxt", "ui_nav_next", false},
    {"joy_sec_prv", "ui_section_previous", false},
    {"joy_sec_nxt", "ui_section_next", false},
    {"scroll_j_x", "ui_scroll_x", true},
    {"scroll_j_y", "ui_scroll_y", true},
    {"shortcut_1", "shortcut_1", false},
    {"shortcut_1h", "shortcut_1_hold", false},
    {"shortcut_2", "shortcut_2", false},
    {"shortcut_2h", "shortcut_2_hold", false},
    {"shortcut_3", "shortcut_3", false},
    {"shortcut_3h", "shortcut_3_hold", false},
    {"shortcut_4", "shortcut_4", false},
    {"shortcut_4h", "shortcut_4_hold", false},
    {"pause", "pause", false},
    {"screenshot", "screenshot", false},
    {"cam1", "camera_1", false},
    {"cam2", "camera_2", false},
    {"cam3", "camera_3", false},
    {"cam4", "camera_4", false},
    {"cam5", "camera_5", false},
    {"cam6", "camera_6", false},
    {"cam7", "camera_7", false},
    {"cam8", "camera_8", false},
    {"camcycle", "camera_cycle", false},
    {"camreset", "camera_reset", false},
    {"camrotate", "camera_rotate", false},
    {"camzoomin", "camera_zoom_in", false},
    {"camzoomout", "camera_zoom_out", false},
    {"camzoom", "camera_zoom_drag", false},
    {"camfwd", "camera_move_forward", false},
    {"camback", "camera_move_back", false},
    {"camleft", "camera_move_left", false},
    {"camright", "camera_move_right", false},
    {"camup", "camera_move_up", false},
    {"camdown", "camera_move_down", false},
    {"lookleft", "look_left", false},
    {"lookright", "look_right", false},
    {"camlr", "camera_look_x", true},
    {"camud", "camera_look_y", true},
    {"j_cam_lk_lr", "camera_look_lr", true},
    {"j_cam_lk_ud", "camera_look_ud", true},
    {"j_cam_mv_lr", "camera_move_lr", true},
    {"j_cam_mv_ud", "camera_move_ud", true},
    {"j_trzoom_in", "trs_zoom_in_axis", true},
    {"j_trzoom_out", "trs_zoom_out_axis", true},
    {"j_tr_cam_res", "trs_camera_reset", false},
    {"j_tr_cam_swi", "trs_camera_switch", false},
    {"j_tr_lights", "trs_lights", false},
    {"j_tr_fullsc", "trs_fullscreen", false},
    {"j_tr_att_tra", "trs_attach_trailer", false},
    {"j_mappan_x", "map_pan_x", true},
    {"j_mappan_y", "map_pan_y", true},
    {"j_mapzom_in", "map_zoom_in_axis", true},
    {"j_mapzom_out", "map_zoom_out_axis", true},
    {"lookpos1", "look_position_1", false},
    {"lookpos2", "look_position_2", false},
    {"lookpos3", "look_position_3", false},
    {"lookpos4", "look_position_4", false},
    {"lookpos5", "look_position_5", false},
    {"lookpos6", "look_position_6", false},
    {"lookpos7", "look_position_7", false},
    {"lookpos8", "look_position_8", false},
    {"lookpos9", "look_position_9", false},
    {"looksteer", "look_steer", false},
    {"lookblink", "look_blinker", false},
    {"steering", "steering", true},
    {"aforward", "throttle", true},
    {"abackward", "brake", true},
    {"clutch", "clutch", true},
    {"activate", "activate", false},
    {"menu", "menu", false},
    {"engine", "engine_toggle", false},
    {"engineelect", "engine_electrics", false},
    {"ignitionoff", "ignition_off", false},
    {"ignitionon", "ignition_on", false},
    {"ignitionstrt", "ignition_start", false},
    {"attach", "attach_trailer", false},
    {"frontsuspup", "suspension_front_up", false},
    {"frontsuspdwn", "suspension_front_down", false},
    {"rearsuspup", "suspension_rear_up", false},
    {"rearsuspdwn", "suspension_rear_down", false},
    {"suspreset", "suspension_reset", false},
    {"horn", "horn", false},
    {"airhorn", "air_horn", false},
    {"lighthorn", "light_flash", false},
    {"beacon", "beacon", false},
    {"motorbrake", "motor_brake", false},
    {"engbraketog", "engine_brake_toggle", false},
    {"engbrakeup", "engine_brake_up", false},
    {"engbrakedwn", "engine_brake_down", false},
    {"trailerbrake", "trailer_brake", false},
    {"retarderup", "retarder_up", false},
    {"retarderdown", "retarder_down", false},
    {"retarder0", "retarder_0", false},
    {"retarder1", "retarder_1", false},
    {"retarder2", "retarder_2", false},
    {"retarder3", "retarder_3", false},
    {"retarder4", "retarder_4", false},
    {"retarder5", "retarder_5", false},
    {"liftaxle", "lift_axle", false},
    {"liftaxlet", "lift_axle_trailer", false},
    {"slideaxlefwd", "slide_axle_forward", false},
    {"slideaxlebwd", "slide_axle_backward", false},
    {"slideaxleman", "slide_axle_manual", false},
    {"trlrsuspup", "trailer_suspension_up", false},
    {"trlrsuspdwn", "trailer_suspension_down", false},
    {"diflock", "differential_lock", false},
    {"rwinopen", "window_right_open", false},
    {"rwinclose", "window_right_close", false},
    {"lwinopen", "window_left_open", false},
    {"lwinclose", "window_left_close", false},
    {"engbrakeauto", "engine_brake_auto", false},
    {"retarderauto", "retarder_auto", false},
    {"embrake", "embrake", false},
    {"laneassmode", "lane_assist_mode", false},
    {"tranpwrmode", "transmission_power_mode", false},
    {"parkingbrake", "parking_brake", false},
    {"handbrake", "handbrake", false},
    {"wipers", "wipers_step_up", false},
    {"wipersback", "wipers_step_down", false},
    {"wipers0", "wipers_level_0", false},
    {"wipers1", "wipers_level_1", false},
    {"wipers2", "wipers_level_2", false},
    {"wipers3", "wipers_level_3", false},
    {"wipers4", "wipers_level_4", false},
    {"cruiectrl", "cruise_control", false},
    {"cruiectrlinc", "cruise_control_increase", false},
    {"cruiectrldec", "cruise_control_decrease", false},
    {"cruiectrlres", "cruise_control_resume", false},
    {"accmode", "acc_mode", false},
    {"laneassist", "lane_assist", false},
    {"light", "lights_cycle", false},
    {"lightoff", "lights_off", false},
    {"lightpark", "lights_parking", false},
    {"lighton", "lights_on", false},
    {"hblight", "high_beam", false},
    {"lblinker", "blinker_left", false},
    {"lblinkerh", "blinker_left_hold", false},
    {"rblinker", "blinker_right", false},
    {"rblinkerh", "blinker_right_hold", false},
    {"flasher4way", "hazard_lights", false},
    {"showmirrors", "show_mirrors", false},
    {"showhud", "show_hud", false},
    {"navmap", "navigation_map", false},
    {"photo_mode", "photo_mode", false},
    {"quicksave", "quick_save", false},
    {"quickload", "quick_load", false},
    {"acaquickr", "aca_quick_reset", false},
    {"radio", "radio", false},
    {"radionext", "radio_next", false},
    {"radioprev", "radio_previous", false},
    {"radioup", "radio_up", false},
    {"radiodown", "radio_down", false},
    {"display", "display_cycle", false},
    {"quickpark", "quick_park", false},
    {"dashmapzoom", "dashboard_map_zoom", false},
    {"tripreset", "trip_reset", false},
    {"sb_activate", "sidebar_activate", false},
    {"sb_swap", "sidebar_swap", false},
    {"infotainment", "infotainment", false},
    {"mapcenter", "map_center", false},
    {"photores", "photo_reset", false},
    {"photomove", "photo_move", false},
    {"phototake", "photo_grab", false},
    {"photofwd", "photo_forward", false},
    {"photobwd", "photo_backward", false},
    {"photoleft", "photo_left", false},
    {"photoright", "photo_right", false},
    {"photoup", "photo_up", false},
    {"photodown", "photo_down", false},
    {"photorolll", "photo_roll_left", false},
    {"photorollr", "photo_roll_right", false},
    {"photosman", "photo_manager", false},
    {"photo_opts", "photo_options", false},
    {"photosnap", "photo_snap", false},
    {"photo_hctrl", "photo_hide_controls", false},
    {"photonames", "photo_names", false},
    {"photozoomout", "photo_zoom_out", false},
    {"photozoomin", "photo_zoom_in", false},
    {"phot_z_j_out", "photo_zoom_out_axis", true},
    {"phot_z_j_in", "photo_zoom_in_axis", true},
    {"album_pgup", "album_page_up", false},
    {"album_pgdn", "album_page_down", false},
    {"album_itup", "album_item_up", false},
    {"album_itdn", "album_item_down", false},
    {"album_itlf", "album_item_left", false},
    {"album_itrg", "album_item_right", false},
    {"album_ithm", "album_item_home", false},
    {"album_iten", "album_item_end", false},
    {"album_itac", "album_item_activate", false},
    {"album_itop", "album_item_options", false},
    {"album_itdl", "album_item_delete", false},
    {"camwalk_for", "walk_forward", false},
    {"camwalk_back", "walk_backward", false},
    {"camwalk_righ", "walk_right", false},
    {"camwalk_left", "walk_left", false},
    {"camwalk_run", "walk_run", false},
    {"camwalk_jump", "walk_jump", false},
    {"camwalk_crou", "walk_crouch", false},
    {"camwalk_lr", "walk_look_lr", true},
    {"camwalk_ud", "walk_look_ud", true},
    {"gearup", "gear_up", false},
    {"geardown", "gear_down", false},
    {"gear0", "gear_neutral", false},
    {"geardrive", "gear_drive", false},
    {"gearreverse", "gear_reverse", false},
    {"gearuphint", "gear_up_hint", false},
    {"geardownhint", "gear_down_hint", false},
    {"transemi", "transmission_semi", false},
    {"drive", "drive", false},
    {"reverse", "reverse", false},
    {"cmirrorsel", "mirror_select_cabin", false},
    {"fmirrorsel", "mirror_select_front", false},
    {"mirroryawl", "mirror_yaw_left", false},
    {"mirroryawr", "mirror_yaw_right", false},
    {"mirrorpitu", "mirror_pitch_up", false},
    {"mirrorpitl", "mirror_pitch_down", false},
    {"mirrorreset", "mirror_reset", false},
    {"quicksel1", "quick_select_1", false},
    {"quicksel2", "quick_select_2", false},
    {"quicksel3", "quick_select_3", false},
    {"quicksel4", "quick_select_4", false},
    {"quicksel5", "quick_select_5", false},
    {"quicksel6", "quick_select_6", false},
    {"quicksel7", "quick_select_7", false},
    {"quicksel8", "quick_select_8", false},
    {"mpptt", "push_to_talk", false},
    {"replayhidec", "replay_hide_controls", false},
    {"gearsel1on", "gear_selector_1_on", false},
    {"gearsel1off", "gear_selector_1_off", false},
    {"gearsel1tgl", "gear_selector_1_toggle", false},
    {"gearsel2on", "gear_selector_2_on", false},
    {"gearsel2off", "gear_selector_2_off", false},
    {"gearsel2tgl", "gear_selector_2_toggle", false},
    {"gear1", "gear_1", false},
    {"gear2", "gear_2", false},
    {"gear3", "gear_3", false},
    {"gear4", "gear_4", false},
    {"gear5", "gear_5", false},
    {"gear6", "gear_6", false},
    {"gear7", "gear_7", false},
    {"gear8", "gear_8", false},
    {"gear9", "gear_9", false},
    {"gear10", "gear_10", false},
    {"gear11", "gear_11", false},
    {"gear12", "gear_12", false},
    {"gear13", "gear_13", false},
    {"gear14", "gear_14", false},
    {"gear15", "gear_15", false},
    {"gear16", "gear_16", false},
    {"adjuster", "adjuster", false},
    {"advmouse", "advisor_mouse", false},
    {"advetamode", "advisor_eta_mode", false},
    {"gar_man", "garage_manager", false},
    {"advzoomin", "advisor_zoom_in", false},
    {"advzoomout", "advisor_zoom_out", false},
    {"advoptions", "advisor_options", false},
    {"services", "advisor_services", false},
    {"assistact1", "assist_action_1", false},
    {"assistact2", "assist_action_2", false},
    {"assistact3", "assist_action_3", false},
    {"assistact4", "assist_action_4", false},
    {"assistact5", "assist_action_5", false},
    {"adj_seats", "adjust_seats", false},
    {"adj_mirrors", "adjust_mirrors", false},
    {"adj_lights", "adjust_lights", false},
    {"adj_uimirror", "adjust_ui_mirror", false},
    {"chat_act", "chat_open", false},
    {"quick_chat", "quick_chat", false},
    {"cycl_zoom", "zoom_cycle", false},
    {"name_tags", "name_tags", false},
    {"headreset", "head_reset", false},
    {"menustereo", "stereo_menu", false},
};

}